server:
  port: 8082

spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://zipkin:9411/}
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.105}
    port: ${rabbitmq.port:5672}
  cloud:
    bus:
      destination: configXchange   
#    stream:
     #rabbit:
#      bindings:
#        webaudit-out: 
#         destination: ex.webaudit
#         group: q.audit
#         producer:
#          bindQueue: false
#          routing-key-expression: '"rk.webaudit.shim.him"'
#          routing-key: '"rk.webaudit.shim.him"'
 #         routingKeyExpression: '''rk.webaudit.shim.him'''

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"